---
image: python:3.11.4-bookworm

stages:
- test
- integration

before_script:
- apt-get update -qq && apt-get install -y -qq ssh golang-go
- pip install poetry==1.4.2
- poetry install

mypy:
  stage: test
  script: poetry run mypy sigsum

pytest:
  stage: test
  script: poetry run pytest --cov

log-integration-test:
  stage: integration
  script: ./integration/test.sh
  artifacts:
    paths:
    - ./integration/*.log
