---
image: python:3.10-bullseye

before_script:
- apt-get update -qq && apt-get install -y -qq ssh

tests:
  script:
  - pip install poetry==1.4.2
  - poetry install
  - poetry run mypy sigsum
  - poetry run pytest --cov
